# Generated by Django 5.0.1 on 2025-10-24 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="이름"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="스태프 권한"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="슈퍼유저 권한"),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="이메일 인증 완료"),
                ),
                (
                    "social_provider",
                    models.CharField(
                        blank=True,
                        choices=[("google", "Google"), ("kakao", "Kakao")],
                        max_length=20,
                        null=True,
                        verbose_name="소셜 로그인 제공자",
                    ),
                ),
                (
                    "social_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="소셜 ID"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="가입일"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="최근 로그인"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="인증 토큰"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료일시")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="사용 완료"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 인증",
                "verbose_name_plural": "이메일 인증 목록",
                "db_table": "email_verifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
