# Generated by Django 5.0.1 on 2025-10-24 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassroomPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="사진 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("image", models.CharField(max_length=500, verbose_name="이미지")),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                ("date", models.DateField(verbose_name="촬영일")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "수업 사진",
                "verbose_name_plural": "수업 사진 목록",
                "db_table": "classroom_photos",
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="제품 ID"
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("short_description", models.TextField(verbose_name="짧은 설명")),
                ("educational_value", models.TextField(verbose_name="교육적 가치")),
                ("classroom_use", models.TextField(verbose_name="수업 활용")),
                (
                    "main_image",
                    models.CharField(max_length=500, verbose_name="메인 이미지"),
                ),
                ("images", models.JSONField(default=list, verbose_name="이미지 목록")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="가격"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="원가",
                    ),
                ),
                ("discount", models.IntegerField(default=0, verbose_name="할인율")),
                (
                    "target_grade",
                    models.CharField(max_length=100, verbose_name="대상 학년"),
                ),
                (
                    "grade_detail",
                    models.CharField(max_length=100, verbose_name="학년 상세"),
                ),
                (
                    "class_time",
                    models.CharField(max_length=100, verbose_name="수업 시간"),
                ),
                (
                    "group_size",
                    models.CharField(max_length=100, verbose_name="그룹 크기"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=3, verbose_name="평점"
                    ),
                ),
                ("reviews", models.IntegerField(default=0, verbose_name="리뷰 수")),
                ("sold_count", models.IntegerField(default=0, verbose_name="판매 수")),
                ("badges", models.JSONField(default=list, verbose_name="배지 목록")),
                ("features", models.JSONField(default=list, verbose_name="특징 목록")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "제품",
                "verbose_name_plural": "제품 목록",
                "db_table": "products",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="상품 ID"
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                ("name", models.CharField(max_length=200, verbose_name="상품명")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="가격"
                    ),
                ),
                ("image", models.CharField(max_length=500, verbose_name="이미지")),
                (
                    "unit",
                    models.CharField(default="개", max_length=50, verbose_name="단위"),
                ),
                (
                    "min_quantity",
                    models.IntegerField(default=1, verbose_name="최소 수량"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "견적 상품",
                "verbose_name_plural": "견적 상품 목록",
                "db_table": "quote_items",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="RelatedClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="수업 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("image", models.CharField(max_length=500, verbose_name="이미지")),
                ("duration", models.CharField(max_length=100, verbose_name="기간")),
                ("difficulty", models.CharField(max_length=50, verbose_name="난이도")),
                ("link", models.CharField(max_length=500, verbose_name="링크")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "관련 수업",
                "verbose_name_plural": "관련 수업 목록",
                "db_table": "related_classes",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="영상 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("thumbnail", models.CharField(max_length=500, verbose_name="썸네일")),
                (
                    "video_url",
                    models.CharField(max_length=500, verbose_name="영상 URL"),
                ),
                ("duration", models.CharField(max_length=50, verbose_name="재생 시간")),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                ("tags", models.JSONField(default=list, verbose_name="태그")),
                ("views", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "교구 영상",
                "verbose_name_plural": "교구 영상 목록",
                "db_table": "videos",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100, verbose_name="작성자")),
                ("rating", models.IntegerField(verbose_name="평점")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("date", models.DateField(verbose_name="작성일")),
                (
                    "helpful_count",
                    models.IntegerField(default=0, verbose_name="도움됨 수"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "제품 리뷰",
                "verbose_name_plural": "제품 리뷰 목록",
                "db_table": "product_reviews",
                "ordering": ["-date"],
            },
        ),
    ]
