# Generated by Django 5.0.1 on 2025-10-24 05:52

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroomphoto",
            name="image",
            field=models.ImageField(
                upload_to=products.models.classroom_photo_path, verbose_name="이미지"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.JSONField(
                default=list,
                help_text="추가 이미지 URL 목록",
                verbose_name="이미지 목록",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                upload_to=products.models.product_image_path, verbose_name="메인 이미지"
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="image",
            field=models.ImageField(
                upload_to=products.models.quote_item_image_path, verbose_name="이미지"
            ),
        ),
        migrations.AlterField(
            model_name="relatedclass",
            name="image",
            field=models.ImageField(
                upload_to=products.models.related_class_image_path,
                verbose_name="이미지",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                upload_to=products.models.video_thumbnail_path, verbose_name="썸네일"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.URLField(
                help_text="YouTube 임베드 URL",
                max_length=500,
                verbose_name="YouTube 영상 URL",
            ),
        ),
    ]
