# Generated by Django 5.0.1 on 2025-10-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.IntegerField(unique=True, verbose_name="아이템 ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("works", "학생 작품"), ("reviews", "수업 후기")],
                        max_length=50,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("image", models.CharField(max_length=500, verbose_name="이미지")),
                (
                    "emoji",
                    models.CharField(blank=True, max_length=10, verbose_name="이모지"),
                ),
                ("author", models.CharField(max_length=100, verbose_name="작성자")),
                ("date", models.DateField(verbose_name="작성일")),
                ("views", models.IntegerField(default=0, verbose_name="조회수")),
                ("likes", models.IntegerField(default=0, verbose_name="좋아요")),
                ("rating", models.IntegerField(default=5, verbose_name="평점")),
                ("details", models.TextField(blank=True, verbose_name="상세 내용")),
                ("images", models.JSONField(default=list, verbose_name="이미지 목록")),
                ("tags", models.JSONField(default=list, verbose_name="태그")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "갤러리 아이템",
                "verbose_name_plural": "갤러리 아이템 목록",
                "db_table": "gallery_items",
                "ordering": ["category", "order", "-date"],
            },
        ),
    ]
