# Generated by Django 5.0.1 on 2026-02-04 03:06

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_id", models.IntegerField(unique=True, verbose_name="후기 ID")),
                ("title", models.CharField(max_length=200, verbose_name="후기 제목")),
                ("content", models.TextField(verbose_name="후기 내용")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=gallery.models.class_review_image_path,
                        verbose_name="후기 이미지",
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="추가 이미지"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=100, verbose_name="작성자"),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[("student", "학생"), ("parent", "학부모")],
                        default="parent",
                        max_length=20,
                        verbose_name="구분",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=200, verbose_name="수강 과정"),
                ),
                (
                    "course_period",
                    models.CharField(max_length=100, verbose_name="수강 기간"),
                ),
                (
                    "instructor",
                    models.CharField(blank=True, max_length=100, verbose_name="강사명"),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        default=5, help_text="1~5점", verbose_name="종합 만족도"
                    ),
                ),
                (
                    "teaching_quality",
                    models.IntegerField(
                        default=5, help_text="1~5점", verbose_name="강의 품질"
                    ),
                ),
                (
                    "curriculum_quality",
                    models.IntegerField(
                        default=5, help_text="1~5점", verbose_name="커리큘럼 품질"
                    ),
                ),
                (
                    "learning_effect",
                    models.IntegerField(
                        default=5, help_text="1~5점", verbose_name="학습 효과"
                    ),
                ),
                ("pros", models.TextField(blank=True, verbose_name="좋았던 점")),
                ("cons", models.TextField(blank=True, verbose_name="개선할 점")),
                (
                    "recommend",
                    models.BooleanField(default=True, verbose_name="추천 여부"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "helpful_count",
                    models.IntegerField(default=0, verbose_name="도움됨 수"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="추천 후기"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="공개"),
                ),
                ("review_date", models.DateField(verbose_name="작성일")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "수업 후기",
                "verbose_name_plural": "수업 후기 목록",
                "db_table": "gallery_class_reviews",
                "ordering": ["-is_featured", "order", "-review_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_id", models.IntegerField(unique=True, verbose_name="작품 ID")),
                ("title", models.CharField(max_length=200, verbose_name="작품명")),
                ("description", models.TextField(verbose_name="작품 설명")),
                (
                    "image",
                    models.ImageField(
                        upload_to=gallery.models.student_work_image_path,
                        verbose_name="대표 이미지",
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="추가 이미지"
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=100, verbose_name="학생명"),
                ),
                ("student_grade", models.CharField(max_length=50, verbose_name="학년")),
                (
                    "student_age",
                    models.IntegerField(blank=True, null=True, verbose_name="나이"),
                ),
                (
                    "technologies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='예: ["Python", "AI", "머신러닝"]',
                        verbose_name="사용 기술",
                    ),
                ),
                (
                    "tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='예: ["micro:bit", "아두이노", "라즈베리파이"]',
                        verbose_name="사용 도구/키트",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "입문"),
                            ("elementary", "초급"),
                            ("intermediate", "중급"),
                            ("advanced", "고급"),
                        ],
                        default="elementary",
                        max_length=20,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "project_period",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="제작 기간"
                    ),
                ),
                (
                    "project_description",
                    models.TextField(blank=True, verbose_name="제작 과정 설명"),
                ),
                (
                    "learning_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='예: ["센서 활용법", "코딩 원리"]',
                        verbose_name="배운 점",
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="조회수")),
                ("likes", models.IntegerField(default=0, verbose_name="좋아요")),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='예: ["AI", "로봇", "게임"]',
                        verbose_name="태그",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="추천 작품"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="공개"),
                ),
                ("created_date", models.DateField(verbose_name="제작 날짜")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "학생 작품",
                "verbose_name_plural": "학생 작품 목록",
                "db_table": "gallery_student_works",
                "ordering": ["-is_featured", "order", "-created_date"],
            },
        ),
    ]
