# Generated by Django 5.0.1 on 2025-10-24 05:52

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=models.ImageField(
                upload_to=gallery.models.gallery_image_path, verbose_name="이미지"
            ),
        ),
    ]
