# Generated by Django 5.0.1 on 2025-10-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurriculumHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("image", models.CharField(max_length=500, verbose_name="이미지")),
                ("href", models.CharField(max_length=500, verbose_name="링크")),
                (
                    "level_badge",
                    models.CharField(max_length=50, verbose_name="레벨 배지"),
                ),
                ("duration", models.CharField(max_length=100, verbose_name="기간")),
                ("size", models.CharField(max_length=100, verbose_name="인원")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "커리큘럼 하이라이트",
                "verbose_name_plural": "커리큘럼 하이라이트 목록",
                "db_table": "curriculum_highlights",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=50, verbose_name="아이콘")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "특징",
                "verbose_name_plural": "특징 목록",
                "db_table": "features",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("image", models.CharField(max_length=500, verbose_name="이미지")),
                (
                    "cta_label",
                    models.CharField(max_length=100, verbose_name="버튼 텍스트"),
                ),
                (
                    "cta_href",
                    models.CharField(max_length=500, verbose_name="버튼 링크"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "히어로 슬라이드",
                "verbose_name_plural": "히어로 슬라이드 목록",
                "db_table": "hero_slides",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomepageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_heading",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="히어로 제목"
                    ),
                ),
                (
                    "hero_subheading",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="히어로 부제목"
                    ),
                ),
                (
                    "carousel_autoplay",
                    models.BooleanField(default=True, verbose_name="자동 재생"),
                ),
                (
                    "carousel_interval_ms",
                    models.IntegerField(default=4000, verbose_name="슬라이드 간격(ms)"),
                ),
                (
                    "carousel_indicators",
                    models.BooleanField(default=True, verbose_name="인디케이터 표시"),
                ),
                (
                    "carousel_pause_on_hover",
                    models.BooleanField(default=True, verbose_name="호버 시 정지"),
                ),
                (
                    "features_heading",
                    models.CharField(
                        default="왜 AI Maker Lab인가요?",
                        max_length=200,
                        verbose_name="특징 섹션 제목",
                    ),
                ),
                (
                    "features_subheading",
                    models.CharField(
                        default="체계적인 커리큘럼과 실습 중심 교육으로 실력을 키웁니다",
                        max_length=500,
                        verbose_name="특징 섹션 부제목",
                    ),
                ),
                (
                    "curriculum_section_badge",
                    models.CharField(
                        default="교육 프로그램",
                        max_length=100,
                        verbose_name="커리큘럼 배지",
                    ),
                ),
                (
                    "curriculum_heading",
                    models.CharField(
                        default="체계적인 교육 커리큘럼",
                        max_length=200,
                        verbose_name="커리큘럼 제목",
                    ),
                ),
                (
                    "curriculum_subheading",
                    models.CharField(
                        default="초급부터 고급까지, 단계별 맞춤 교육 프로그램",
                        max_length=500,
                        verbose_name="커리큘럼 부제목",
                    ),
                ),
                (
                    "curriculum_view_all_label",
                    models.CharField(
                        default="전체 커리큘럼 보기",
                        max_length=100,
                        verbose_name="전체보기 버튼",
                    ),
                ),
                (
                    "outreach_heading",
                    models.CharField(
                        default="AI Maker Lab의 찾아가는 코딩 수업!",
                        max_length=200,
                        verbose_name="출강 섹션 제목",
                    ),
                ),
                (
                    "outreach_subheading",
                    models.CharField(
                        default="코딩교육이 필요한 공간에, 여기저기 달려갑니다.",
                        max_length=500,
                        verbose_name="출강 섹션 부제목",
                    ),
                ),
                (
                    "outreach_grades",
                    models.JSONField(default=list, verbose_name="대상 학년"),
                ),
                (
                    "outreach_image",
                    models.CharField(
                        default="/modern-coding-education-classroom-with-computers.jpg",
                        max_length=500,
                        verbose_name="출강 이미지",
                    ),
                ),
                (
                    "outreach_card_title",
                    models.CharField(
                        default="온라인 스마트 시대 열기",
                        max_length=200,
                        verbose_name="출강 카드 제목",
                    ),
                ),
                (
                    "outreach_card_lines",
                    models.JSONField(default=list, verbose_name="출강 카드 내용"),
                ),
                (
                    "outreach_hashtags",
                    models.JSONField(default=list, verbose_name="해시태그"),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="AI Maker Lab",
                        max_length=100,
                        verbose_name="사이트 이름",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "홈페이지 설정",
                "verbose_name_plural": "홈페이지 설정",
                "db_table": "homepage_config",
            },
        ),
        migrations.CreateModel(
            name="IntroVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200, verbose_name="제목")),
                ("subheading", models.CharField(max_length=500, verbose_name="부제목")),
                (
                    "youtube_title",
                    models.CharField(max_length=200, verbose_name="영상 제목"),
                ),
                (
                    "youtube_embed_url",
                    models.URLField(verbose_name="YouTube 임베드 URL"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "소개 영상",
                "verbose_name_plural": "소개 영상 목록",
                "db_table": "intro_videos",
            },
        ),
        migrations.CreateModel(
            name="OutreachStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_icon", models.CharField(max_length=50, verbose_name="아이콘")),
                ("value", models.CharField(max_length=100, verbose_name="값")),
                ("caption", models.CharField(max_length=200, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "출강 통계",
                "verbose_name_plural": "출강 통계 목록",
                "db_table": "outreach_stats",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("inquiry", "문의"),
                            ("curriculum", "커리큘럼"),
                            ("products", "제품"),
                            ("about", "소개"),
                        ],
                        max_length=50,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("icon", models.CharField(max_length=50, verbose_name="아이콘")),
                ("href", models.CharField(max_length=500, verbose_name="링크")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "빠른 링크",
                "verbose_name_plural": "빠른 링크 목록",
                "db_table": "quick_links",
                "ordering": ["order"],
            },
        ),
    ]
