# Generated by Django 5.0.1 on 2025-10-24 05:52

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculumhighlight",
            name="image",
            field=models.ImageField(
                upload_to=home.models.curriculum_highlight_image_path,
                verbose_name="이미지",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="image",
            field=models.ImageField(
                upload_to=home.models.hero_slide_image_path, verbose_name="이미지"
            ),
        ),
    ]
