# Generated by Django 5.0.1 on 2025-10-24 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai-education", "AI 교육"),
                            ("app-inventor", "앱 인벤터"),
                            ("arduino", "아두이노"),
                            ("raspberry-pi", "라즈베리파이"),
                            ("science", "과학 교육"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "badge",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="배지 텍스트"
                    ),
                ),
                (
                    "gradient_class",
                    models.CharField(max_length=200, verbose_name="그라데이션 클래스"),
                ),
                (
                    "meta_title",
                    models.CharField(max_length=200, verbose_name="메타 제목"),
                ),
                ("meta_description", models.TextField(verbose_name="메타 설명")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "커리큘럼",
                "verbose_name_plural": "커리큘럼 목록",
                "db_table": "curriculum",
                "ordering": ["order", "category"],
            },
        ),
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info_id", models.CharField(max_length=50, verbose_name="정보 ID")),
                ("icon", models.CharField(max_length=50, verbose_name="아이콘")),
                (
                    "icon_color",
                    models.CharField(max_length=50, verbose_name="아이콘 색상"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="라벨")),
                ("value", models.CharField(max_length=200, verbose_name="값")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_info_items",
                        to="curriculum.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name": "과정 정보",
                "verbose_name_plural": "과정 정보 목록",
                "db_table": "course_info",
                "ordering": ["curriculum", "order"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(max_length=50, verbose_name="프로젝트 ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="이미지 경로"
                    ),
                ),
                ("difficulty", models.CharField(max_length=50, verbose_name="난이도")),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="대학 연계"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="curriculum.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name": "커리큘럼 프로젝트",
                "verbose_name_plural": "커리큘럼 프로젝트 목록",
                "db_table": "curriculum_projects",
                "ordering": ["curriculum", "order"],
            },
        ),
        migrations.CreateModel(
            name="EducationRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement_id",
                    models.CharField(max_length=50, verbose_name="조건 ID"),
                ),
                ("icon", models.CharField(max_length=50, verbose_name="아이콘")),
                (
                    "icon_color",
                    models.CharField(max_length=50, verbose_name="아이콘 색상"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.CharField(max_length=500, verbose_name="설명")),
                ("details", models.JSONField(default=list, verbose_name="세부 사항")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_requirements",
                        to="curriculum.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name": "교육 조건",
                "verbose_name_plural": "교육 조건 목록",
                "db_table": "education_requirements",
                "ordering": ["curriculum", "order"],
            },
        ),
        migrations.CreateModel(
            name="GradeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=50, verbose_name="과정 ID")),
                (
                    "course_name",
                    models.CharField(max_length=200, verbose_name="과정명"),
                ),
                ("description", models.CharField(max_length=500, verbose_name="설명")),
                ("difficulty", models.CharField(max_length=50, verbose_name="난이도")),
                ("duration", models.CharField(max_length=50, verbose_name="기간")),
                (
                    "elementary_mid",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="초3-4"
                    ),
                ),
                (
                    "elementary_high",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="초5-6"
                    ),
                ),
                (
                    "middle_low",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="중1-2"
                    ),
                ),
                (
                    "middle_high",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="중3"
                    ),
                ),
                (
                    "high",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="고등"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_recommendations",
                        to="curriculum.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name": "학년별 추천",
                "verbose_name_plural": "학년별 추천 목록",
                "db_table": "grade_recommendations",
                "ordering": ["curriculum", "order"],
            },
        ),
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_id", models.CharField(max_length=50, verbose_name="목표 ID")),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("skills", models.JSONField(default=list, verbose_name="기술 목록")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals",
                        to="curriculum.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name": "학습 목표",
                "verbose_name_plural": "학습 목표 목록",
                "db_table": "learning_goals",
                "ordering": ["curriculum", "order"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.CharField(max_length=50, verbose_name="카테고리 ID"),
                ),
                (
                    "category_title",
                    models.CharField(max_length=200, verbose_name="카테고리 제목"),
                ),
                (
                    "material_id",
                    models.CharField(max_length=50, verbose_name="자료 ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.CharField(max_length=500, verbose_name="설명")),
                ("icon", models.CharField(max_length=50, verbose_name="아이콘")),
                ("format", models.CharField(max_length=50, verbose_name="포맷")),
                (
                    "pages",
                    models.CharField(max_length=50, verbose_name="페이지/파일 수"),
                ),
                ("size", models.CharField(max_length=50, verbose_name="크기")),
                (
                    "download_url",
                    models.CharField(max_length=500, verbose_name="다운로드 URL"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="curriculum.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name": "수업 자료",
                "verbose_name_plural": "수업 자료 목록",
                "db_table": "materials",
                "ordering": ["curriculum", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tab_id", models.CharField(max_length=50, verbose_name="탭 ID")),
                ("label", models.CharField(max_length=100, verbose_name="라벨")),
                ("duration", models.CharField(max_length=50, verbose_name="기간")),
                ("description", models.TextField(verbose_name="설명")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="curriculum.curriculumproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트 탭",
                "verbose_name_plural": "프로젝트 탭 목록",
                "db_table": "project_tabs",
                "ordering": ["project", "order"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(max_length=50, verbose_name="모듈 ID")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("duration", models.CharField(max_length=50, verbose_name="소요 시간")),
                ("detail_description", models.TextField(verbose_name="상세 설명")),
                ("topics", models.JSONField(default=list, verbose_name="주제 목록")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="curriculum.projecttab",
                    ),
                ),
            ],
            options={
                "verbose_name": "수업 모듈",
                "verbose_name_plural": "수업 모듈 목록",
                "db_table": "modules",
                "ordering": ["tab", "order"],
            },
        ),
    ]
