# Generated by Django 5.0.1 on 2025-10-24 05:52

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculumproject",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=curriculum.models.curriculum_project_image_path,
                verbose_name="이미지",
            ),
        ),
    ]
