# Generated by Django 5.0.1 on 2025-10-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_id",
                    models.IntegerField(unique=True, verbose_name="문의 ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "접수대기"),
                            ("reviewing", "검토중"),
                            ("quoted", "견적발송"),
                            ("confirmed", "확정"),
                            ("completed", "완료"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="상태",
                    ),
                ),
                ("date", models.DateField(verbose_name="문의일")),
                (
                    "requester_name",
                    models.CharField(max_length=100, verbose_name="문의자 이름"),
                ),
                (
                    "requester_contact",
                    models.CharField(max_length=50, verbose_name="연락처"),
                ),
                (
                    "requester_email",
                    models.EmailField(max_length=254, verbose_name="이메일"),
                ),
                ("course", models.CharField(max_length=200, verbose_name="수업 과정")),
                ("grade", models.CharField(max_length=100, verbose_name="대상 학년")),
                (
                    "participant_count",
                    models.CharField(max_length=100, verbose_name="참여 인원"),
                ),
                ("location", models.CharField(max_length=500, verbose_name="장소")),
                ("budget", models.CharField(max_length=100, verbose_name="예산")),
                (
                    "preferred_date",
                    models.DateField(blank=True, null=True, verbose_name="희망 날짜"),
                ),
                (
                    "preferred_time",
                    models.TimeField(blank=True, null=True, verbose_name="희망 시간"),
                ),
                (
                    "duration",
                    models.CharField(max_length=100, verbose_name="희망 기간"),
                ),
                ("content", models.TextField(verbose_name="문의 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "수업 문의",
                "verbose_name_plural": "수업 문의 목록",
                "db_table": "inquiries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="일정 ID"
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("weekday", "주중 수업"), ("weekend", "주말 수업")],
                        max_length=50,
                        verbose_name="일정 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("course", models.CharField(max_length=200, verbose_name="수업 과정")),
                ("instructor", models.CharField(max_length=100, verbose_name="강사")),
                ("date", models.DateField(verbose_name="날짜")),
                ("start_time", models.TimeField(verbose_name="시작 시간")),
                ("end_time", models.TimeField(verbose_name="종료 시간")),
                ("duration", models.CharField(max_length=100, verbose_name="기간")),
                (
                    "target_grade",
                    models.CharField(max_length=100, verbose_name="대상 학년"),
                ),
                ("max_students", models.IntegerField(verbose_name="최대 인원")),
                (
                    "current_students",
                    models.IntegerField(default=0, verbose_name="현재 인원"),
                ),
                ("location", models.CharField(max_length=500, verbose_name="장소")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("requirements", models.JSONField(default=list, verbose_name="준비물")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="수강 가능"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "수업 일정",
                "verbose_name_plural": "수업 일정 목록",
                "db_table": "schedules",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
